### ISSUE TITLE
incorrect chances when reading percent chances via API for block and chest loot.

### ISSUE THREAD

**Issue by walksanatora** [fzzyhmstrs/EMI_loot#46]
currently, when reading API it always reads as having a 100% chance to get that item. when in reality the % is diffrent.
this should hopefully be a simple change in
[BlockLootRecipe.java](https://github.com/fzzyhmstrs/EMI_loot/blob/master/src/main/java/fzzyhmstrs/emi_loot/emi/BlockLootRecipe.java#L39)
probably just weight/100f to get the actual chance

**Comment by fzzyhmstrs** [comment]
You might be conflating a conditional chance and the rolled weight? I'd have to take a closer look, and an example of the exact case you are checking (including entire loot table) would help. If there is an item that is the only item in a pool, but has a Condition that it only appears X% of the time, it will roll "100%" of the time per that tooltip, with the condition added on separately that the pool itself only rolls "X%" (the icons next to the item)

**Comment by walksanatora** [comment]
here is a example. block drops for leaves.
```json
    {
        "id": {
            "namespace": "emi",
            "path": "emi_loot/block_drops/minecraft/blocks/oak_leaves"
        },
        "type": {
            "namespace": "emi_loot",
            "path": "block_drops"
        },
        "input": [],
        "output": [
            {
                "id": {
                    "namespace": "minecraft",
                    "path": "oak_leaves"
                },
                "ammount": 1,
                "chance": 1.0
            },
            {
                "id": {
                    "namespace": "minecraft",
                    "path": "apple"
                },
                "ammount": 1,
                "chance": 1.0
            },
            {
                "id": {
                    "namespace": "minecraft",
                    "path": "stick"
                },
                "ammount": 1,
                "chance": 1.0
            },
            {
                "id": {
                    "namespace": "minecraft",
                    "path": "oak_sapling"
                },
                "ammount": 1,
                "chance": 1.0
            }
        ]
    }
```
leaves do not have a 100% chance to drop a sapling
but the UI and such report it as 100% (or am I just going insane)
and in the case of starter chest loot. the bonus chest only has a 29.2% chance per-slot to have oak logs. but it still has 100% according to the EMI recipe

**Comment by fzzyhmstrs** [comment]
That "chance" field in that output has nothing to do with drop chance (which can be non-deterministic), that's "chance" as defined in EMI's API. Saplings in particular are a tricky example, as they are defined with a "Table Bonus with Fortune" condition, which isn't easily definable because it uses a lookup table. The condition tooltip thus only says "Drops increased with fortune", and that's all it can easily say. In general, as I mentioned, the combination of condition tip and stated chance is the "real" chance.

Wheat seeds for example; these things need to be considered together. It Drops 100% of an item 12.5% of the time.:
![image](https://github.com/user-attachments/assets/9049bb98-c1f5-4295-854a-0ad3052ab245)
![image](https://github.com/user-attachments/assets/7a2dbe48-7976-42b4-b1cd-bdf07c49943b)

 With the often non-deterministic reality of loot tables, this is about as clear as I can get, since with this same example, drop rate is also increased with fortune, making "chance" non-constant
![image](https://github.com/user-attachments/assets/befc5924-7296-4bfd-bc81-1fd8d72561c6)
